import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { SocialIcon } from "react-social-icons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <NavBar />
          <SocialLinks />
        </header>
        {children}
      </body>
    </html>
  );
}

function NavBar() {
  const navLinks = [
    { href: "/", label: "Perry Fardella" },
    { href: "/blog", label: "Blog" },
    { href: "/projects", label: "Projects" },
  ];

  return (
    <nav>
      <ul>
        {navLinks.map((link) => (
          <li key={link.href}>
            <Link href={link.href}>{link.label}</Link>
          </li>
        ))}
      </ul>
    </nav>
  );
}

function SocialLinks() {
  const socialLinks = [
    { href: "https://github.com/perryfardella", label: "Github" },
    { href: "https://www.linkedin.com/in/perry-fardella/", label: "LinkedIn" },
    { href: "https://x.com/perryfardella", label: "X" },
  ];

  return (
    <nav>
      <ul>
        {socialLinks.map((link) => (
          <li key={link.href + link.label}>
            <SocialIcon
              url={link.href}
              target="_blank"
              rel="noopener noreferrer"
              bgColor="transparent"
              fgColor="#9ca3af"
            />
          </li>
        ))}
      </ul>
    </nav>
  );
}
